version: '3.8'

services:
  app:
    image: node:20
    container_name: bunker-nestjs-app
    command: bash -c "npm install && npm run start:dev"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: bunker

  db:
    image: mysql:8.0
    container_name: bunker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bunker
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - .:/app

volumes:
  db-data:
